# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest with Flake8

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11", "3.12"]
        numpy_ver: ["latest"]
        test_config: ["latest"]
        include:
          # SPEC0000 compliance settings
          - python-version: "3.10"
            numpy_ver: "1.24"
            pandas_ver: "1.5.0"
            scipy_ver: "1.10.0"
            os: ubuntu-latest
            test_config: "SPEC0"

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} with numpy ${{ matrix.numpy_ver }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install SPEC0 dependencies
      if: ${{ matrix.test_config == 'SPEC0'}}
      run: |
        pip install numpy==${{ matrix.numpy_ver }}
        pip install pandas==${{ matrix.pandas_ver }}
        pip install scipy==${{ matrix.scipy_ver }}
        pip install --upgrade-strategy only-if-needed .

    - name: Install standard dependencies
      if: ${{ matrix.test_config == 'latest'}}
      run: pip install .

